import './globals.css'
import '../../src/styles/global.css'

export const metadata = {
  title: 'Super AGI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
